asmfinal/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace asmfinal.Models
{
    public class Login : ASMContext
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Phải nhập")]
        [Display(Name = "Tên")]
        [Column(TypeName = "nvarchar(100)")]
        public string name { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "{0} Phải nhập")]
        [Display(Name = "Email của bạn")]
        public string email { get; set; }

        [Required(ErrorMessage = "{0} Phải nhập")]
        [Display(Name = "Mật khẩu")]
        [Column(TypeName = "varchar(100)")]
        public string password { get; set; }
    }
}

asmfinal/Controllers/DanhmucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asmfinal.Models;
using Microsoft.AspNetCore.Http;

namespace asmfinal.Controllers
{
    public class DanhmucController : Controller
    {
        private readonly ASMContext _context;

        public DanhmucController(ASMContext context)
        {
            _context = context;
        }
      
        // GET: Danhmuc 
        [HttpGet("/manage/danhmuc")]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("tenNv") == null)
            {
                TempData["message"] = "Vui lòng đăng nhập tài khoản admin";
                return RedirectToAction("Admin", controllerName: "Account");
            }
            return View(await _context.Danhmuc.ToListAsync());
        }
        //GET: Danhmuc/Details/{Id?}
        [HttpGet("/manage/Danhmuc/Details/{Id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc
                .FirstOrDefaultAsync(m => m.MaDm == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);
        }

        // GET: Danhmuc/Create
        [HttpGet("/manage/Danhmuc/Create")]
        public IActionResult Create()
        {
            return View();
        }
        // POST: Danhmuc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/manage/Danhmuc/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDm,TenDm")] Danhmuc danhmuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhmuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Danhmuc/Edit/5
        [HttpGet("/manage/Danhmuc/Edit/{id?}")]
        public async Task<IActionResult> Edit(int? id) // nhung74 ham co tham so m sua z {id?}
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc.FindAsync(id);
            if (danhmuc == null)
            {
                return NotFound();
            }
            return View(danhmuc);
        }

        // POST: Danhmuc/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("manage/Danhmuc/Edit/{id?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaDm,TenDm")] Danhmuc danhmuc)
        {
            if (id != danhmuc.MaDm)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhmuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhmucExists(danhmuc.MaDm))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Danhmuc/Delete/5
        [HttpGet("/manage/Danhmuc/Delete/{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc
                .FirstOrDefaultAsync(m => m.MaDm == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);                
        }

        // POST: Danhmuc/Delete/5
        [HttpPost("/manage/Danhmuc/Delete/{id?}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhmuc = await _context.Danhmuc.FindAsync(id);
            _context.Danhmuc.Remove(danhmuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //cai1 nay khong suaa
        private bool DanhmucExists(int id)
        {
            return _context.Danhmuc.Any(e => e.MaDm == id);
        }
    }
}

asmfinal/Controllers/GiohangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asmfinal.Models;
using Microsoft.AspNetCore.Http;

namespace asmfinal.Controllers
{
    public class GiohangController : Controller
    {
        private readonly ASMContext _context;

        public GiohangController(ASMContext context)
        {
            _context = context;
        }

        // GET: Giohang
        [HttpGet("/manage/giohang")]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("tenNv") == null)
            {
                TempData["message"] = "Vui lòng đăng nhập tài khoản admin";
                return RedirectToAction("Admin", controllerName: "Account");
            }
            var aSMContext = _context.Giohang.Include(g => g.MaHangNavigation).Include(g => g.MaKhachNavigation);
            return View(await aSMContext.ToListAsync());
        }

        // GET: Giohang/Details/5
        [HttpGet("/manage/Giohang/Details/{id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giohang = await _context.Giohang
                .Include(g => g.MaHangNavigation)
                .Include(g => g.MaKhachNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (giohang == null)
            {
                return NotFound();
            }

            return View(giohang);
        }

        // GET: Giohang/Create
        [HttpGet("/manage/Giohang/Create")]
        public IActionResult Create()
        {
            ViewData["MaHang"] = new SelectList(_context.Sanpham, "MaHang", "TenHang");
            ViewData["MaKhach"] = new SelectList(_context.Khachhang, "MaKhach", "DiaChi");
            return View();
        }

        // POST: Giohang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/manage/Giohang/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHang,SoLuong,MaKhach")] Giohang giohang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(giohang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaHang"] = new SelectList(_context.Sanpham, "MaHang", "TenHang", giohang.MaHang);
            ViewData["MaKhach"] = new SelectList(_context.Khachhang, "MaKhach", "DiaChi", giohang.MaKhach);
            return View(giohang);
        }

        // GET: Giohang/Edit/5
        [HttpGet("/manage/Giohang/Edit/{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giohang = await _context.Giohang.FindAsync(id);
            if (giohang == null)
            {
                return NotFound();
            }
            ViewData["MaHang"] = new SelectList(_context.Sanpham, "MaHang", "TenHang", giohang.MaHang);
            ViewData["MaKhach"] = new SelectList(_context.Khachhang, "MaKhach", "DiaChi", giohang.MaKhach);
            return View(giohang);
        }

        // POST: Giohang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("manage/Giohang/Edit/{id?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHang,SoLuong,MaKhach")] Giohang giohang)
        {
            if (id != giohang.MaHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(giohang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GiohangExists(giohang.MaHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaHang"] = new SelectList(_context.Sanpham, "MaHang", "TenHang", giohang.MaHang);
            ViewData["MaKhach"] = new SelectList(_context.Khachhang, "MaKhach", "DiaChi", giohang.MaKhach);
            return View(giohang);
        }

        // GET: Giohang/Delete/5
        [HttpGet("/manage/Giohang/Detele/{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giohang = await _context.Giohang
                .Include(g => g.MaHangNavigation)
                .Include(g => g.MaKhachNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (giohang == null)
            {
                return NotFound();
            }

            return View(giohang);
        }

        // POST: Giohang/Delete/5

        [HttpPost("/manage/Giohang/Delete/{id?}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var giohang = await _context.Giohang.FindAsync(id);
            _context.Giohang.Remove(giohang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GiohangExists(int id)
        {
            return _context.Giohang.Any(e => e.MaHang == id);
        }
    }
}

asmfinal/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asmfinal.Models;
using Microsoft.AspNetCore.Http;

namespace asmfinal.Controllers
{
    public class SanphamController : Controller
    {
        private readonly ASMContext _context;

        public SanphamController(ASMContext context)
        {
            _context = context;
        }

        // GET: Sanpham
        [HttpGet("/manage/sanpham")]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("tenNv") == null)
            {
                TempData["message"] = "Vui lòng đăng nhập tài khoản admin";
                return RedirectToAction("Admin", controllerName: "Account");
            }
            var aSMContext = _context.Sanpham.Include(s => s.MaDmNavigation);
            return View(await aSMContext.ToListAsync());
        }

        // GET: Sanpham/Details/5
        [HttpGet("/manage/Sanpham/Details/{id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (sanpham == null)
            {
                return NotFound();
            }

            return View(sanpham);
        }

        // GET: Sanpham/Create
        [HttpGet("/manage/Sanpham/Create")]
        public IActionResult Create()
        {
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "TenDm");
            return View();
        }

        // POST: Sanpham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/manage/Sanpham/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHang,TenHang,SoLuong,HinhAnh,DonGiaNhap,DonGiaBan,MaDm")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanpham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "TenDm", sanpham.MaDm);
            return View(sanpham);
        }

        // GET: Sanpham/Edit/5
        [HttpGet("/manage/Sanpham/Edit/{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham.FindAsync(id);
            if (sanpham == null)
            {
                return NotFound();
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "TenDm", sanpham.MaDm);
            return View(sanpham);
        }

        // POST: Sanpham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("manage/Sanpham/Edit/{id?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHang,TenHang,SoLuong,HinhAnh,DonGiaNhap,DonGiaBan,MaDm")] Sanpham sanpham)
        {
            if (id != sanpham.MaHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanpham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanphamExists(sanpham.MaHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "TenDm", sanpham.MaDm);
            return View(sanpham);
        }

        // GET: Sanpham/Delete/5
        [HttpGet("/manage/Sanpham/Detele/{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (sanpham == null)
            {
                return NotFound();
            }

            return View(sanpham);
        }

        // POST: Sanpham/Delete/5
        [HttpPost("/manage/Sanpham/Delete/{id?}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanpham = await _context.Sanpham.FindAsync(id);
            _context.Sanpham.Remove(sanpham);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanphamExists(int id)
        {
            return _context.Sanpham.Any(e => e.MaHang == id);
        }
    }
}

asmfinal/Views/Shared/_LayoutManage.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Blank Page - Brand</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="/assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/fontawesome5-overrides.min.css">
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-laugh-wink"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>ASM C#</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item"><a asp-controller="Sanpham" class="nav-link"><i class="far fa-user-circle"></i><span>Sản phẩm</span></a></li>
                    <li class="nav-item"><a asp-controller="Danhmuc" class="nav-link" ><i class="far fa-user-circle"></i><span>Danh mục</span></a></li>
                    <li class="nav-item"><a asp-controller="Chitiethoadon" class="nav-link"><i class="far fa-user-circle"></i><span>Hoá đơn</span></a></li>
                    <li class="nav-item"><a asp-controller="Giohang" class="nav-link" ><i class="far fa-user-circle"></i><span>Giỏ hàng</span></a></li>
                    <li class="nav-item"><a asp-controller="Khachhang" class="nav-link" ><i class="far fa-user-circle"></i><span>Khách hàng</span></a></li>
                    <li class="nav-item"><a asp-controller="" class="nav-link"><i class="far fa-user-circle"></i><span>Nhân viên</span></a></li>

                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <form class="d-none d-sm-inline-block me-auto ms-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..."><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                        </form>
                        <ul class="navbar-nav flex-nowrap ms-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-end p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="me-auto navbar-search w-100">
                                        <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                                            <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item dropdown no-arrow mx-1">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><span class="badge bg-danger badge-counter">3+</span><i class="fas fa-bell fa-fw"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
                                        <h6 class="dropdown-header">alerts center</h6><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="me-3">
                                                <div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 12, 2019</span>
                                                <p>A new monthly report is ready to download!</p>
                                            </div>
                                        </a><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="me-3">
                                                <div class="bg-success icon-circle"><i class="fas fa-donate text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 7, 2019</span>
                                                <p>$290.29 has been deposited into your account!</p>
                                            </div>
                                        </a><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="me-3">
                                                <div class="bg-warning icon-circle"><i class="fas fa-exclamation-triangle text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 2, 2019</span>
                                                <p>Spending Alert: We've noticed unusually high spending for your account.</p>
                                            </div>
                                        </a><a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item dropdown no-arrow mx-1">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><span class="badge bg-danger badge-counter">7</span><i class="fas fa-envelope fa-fw"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
                                        <h6 class="dropdown-header">alerts center</h6><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="dropdown-list-image me-3">
                                                <img class="rounded-circle" src="assets/img/avatars/avatar4.jpeg">
                                                <div class="bg-success status-indicator"></div>
                                            </div>
                                            <div class="fw-bold">
                                                <div class="text-truncate"><span>Hi there! I am wondering if you can help me with a problem I've been having.</span></div>
                                                <p class="small text-gray-500 mb-0">Emily Fowler - 58m</p>
                                            </div>
                                        </a><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="dropdown-list-image me-3">
                                                <img class="rounded-circle" src="assets/img/avatars/avatar2.jpeg">
                                                <div class="status-indicator"></div>
                                            </div>
                                            <div class="fw-bold">
                                                <div class="text-truncate"><span>I have the photos that you ordered last month!</span></div>
                                                <p class="small text-gray-500 mb-0">Jae Chun - 1d</p>
                                            </div>
                                        </a><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="dropdown-list-image me-3">
                                                <img class="rounded-circle" src="assets/img/avatars/avatar3.jpeg">
                                                <div class="bg-warning status-indicator"></div>
                                            </div>
                                            <div class="fw-bold">
                                                <div class="text-truncate"><span>Last month's report looks great, I am very happy with the progress so far, keep up the good work!</span></div>
                                                <p class="small text-gray-500 mb-0">Morgan Alvarez - 2d</p>
                                            </div>
                                        </a><a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="dropdown-list-image me-3">
                                                <img class="rounded-circle" src="assets/img/avatars/avatar5.jpeg">
                                                <div class="bg-success status-indicator"></div>
                                            </div>
                                            <div class="fw-bold">
                                                <div class="text-truncate"><span>Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</span></div>
                                                <p class="small text-gray-500 mb-0">Chicken the Dog · 2w</p>
                                            </div>
                                        </a><a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                                    </div>
                                </div>
                                <div class="shadow dropdown-list dropdown-menu dropdown-menu-end" aria-labelledby="alertsDropdown"></div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    @await Html.PartialAsync("_loginAdmin")
                                                                <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
                                                                    <a class="dropdown-item" asp-controller="Home"><i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Trang Khách hàng</a>
                                                                    <div class="dropdown-divider"></div><a class="dropdown-item" asp-controller="account" asp-action="logoutAdmin" ><i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400 text-danger"></i>&nbsp;Logout</a>
                                                                </div>
                                                            </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © Brand 2022</span></div>
                </div>
            </footer>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/theme.js"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>

asmfinal/Views/Shared/_alert.cshtml
@{

    string message = TempData["message"] as string;

    string messageType = TempData["messageType"] as string;
    messageType ??= "success";





}

@if (message != null)
{
    <div class="alert alert-@messageType">@message</div>
}

asmfinal/Views/Shared/_countcart.cshtml
@{

    var Cart = SessionHelper.GetObjectFormJson<List<ItemCart>>(HttpContextAccessor.HttpContext.Session,"cart");


}
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@if (Cart != null)
{

<div style="position: absolute; top: -15px; right: -15px;
                        width: 20px; height: 20px; border-radius: 50%;
                        background: red; color: white;">@Cart.Count()</div>

}

asmfinal/Views/Shared/_danhmucpartical.cshtml
@{
    var danhmucs = ViewData["danhmuc"] as List<Danhmuc>;
}

@if (danhmucs != null )
{

     

                foreach (var item in danhmucs)
                {
                <div>
                    <a asp-action="index" asp-route-id="@item.MaDm">@item.TenDm</a>
                </div>
                }

}